tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "sqlite"
brew "ansible"
brew "asdf"
brew "awscli"
brew "json-c"
brew "pcre2"
brew "direnv"
brew "fzf"
brew "gh"
brew "git"
brew "git-standup"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "jq"
brew "ruby"
brew "macvim"
brew "mas"
brew "tidy-html5"
brew "tree"
brew "zlib"
cask "1password-cli"
cask "docker"
cask "iterm2"
cask "ngrok"
cask "vagrant"
cask "visual-studio-code"
mas "Airmail", id: 918858936
mas "Evernote", id: 406056744
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Prime Video", id: 545519333
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Valentina Studio", id: 604825918
mas "Xcode", id: 497799835
