# Enable color by default in Terminal output
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export CLICOLOR LSCOLORS

# CLI SETTINGS
export EDITOR=vim

# PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
# New zshell propt
PROMPT="%n@%M %~ %# "

export PATH="$HOME/bin:$PATH"

## asdf configuration
export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# append completions to fpath
fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

