. "$HOME/.bashrc"

export PATH=$HOME/.npm-packages/bin:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/tomcat/8.0.9/bin:$HOME/.rbenv/bin:$EVERNOTE_PROJ_ROOT/DevTools/bin:$PATH

if
  which rbenv > /dev/null; then eval "$(rbenv init -)"; 
fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Allow gulp to watch the number of files we need
ulimit -S -n 1024

## Add git completion
source /usr/local/etc/bash_completion.d/git-completion.bash
