. "$HOME/.bashrc"

## Load pyenv-virtualenv
# export PATH=$HOME/.pyenv:$PATH
# 
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
# 
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Add Hombrew to path
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

#export PATH=$HOME/.npm-packages/bin:/usr/local/bin:/usr/local/sbin:$HOME/.rbenv/bin:$PATH

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Allow gulp to watch the number of files we need
ulimit -S -n 1024

## Load rbenv
export PATH=$HOME/.rbenv/bin:$PATH

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

## Load nvm
#export NVM_DIR=~/.nvm
#source $(brew --prefix nvm)/nvm.sh

## Load pkg config
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH

## Watchman config
export WATCHMAN_CONFIG_FILE=$HOME/.watchmanconfig.json

## Include asdf
. $(brew --prefix asdf)/libexec/asdf.sh
#
## Add global npm bin to path
export PATH=$HOME/.npm-global/bin:$PATH

## Load direnv
eval "$(direnv hook bash)"
