# Enable color by default in Terminal output
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export CLICOLOR LSCOLORS

export EDITOR=vim

[ ! -f "$HOME/.bashrc.local" ] || . "$HOME/.bashrc.local"
[ ! -f "$HOME/.bashrc.completion" ] || . "$HOME/.bashrc.completion"

# Load nvm
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
