# Enable color by default in Terminal output
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export CLICOLOR LSCOLORS

export EDITOR=vim

# PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

[ ! -f "$HOME/.bashrc.local" ] || . "$HOME/.bashrc.local"
[ ! -f "$HOME/.bashrc.completion" ] || . "$HOME/.bashrc.completion"
